using System;
using System.Collections.Generic;
using System.Text;

namespace HANEL.MODEL.Dtos.Finance.Budget
{
    public class BudgetAndActualWithMonthsDto : Entities.Finance.Budget
    {
        public string ForeingId { get; set; }
        public string BranchName { get; set; }
        public string BudgetMainGroup { get; set; }
        public string BudgetSubGroup { get; set; }
        public string BudgetMainCodeDesc { get; set; }
        public string BudgetSubCodeDesc { get; set; }
        public string BudgetCurrencyCode { get; set; }
        public string LastBudgetCurrencyCode { get; set; }
        public string ActualCurrencyCode { get; set; }
        public decimal BudgetSummary { get; set; }
        public decimal BudgetOcak { get; set; }
        public decimal BudgetSubat { get; set; }
        public decimal BudgetMart { get; set; }
        public decimal BudgetNisan { get; set; }
        public decimal BudgetMayis { get; set; }
        public decimal BudgetHaziran { get; set; }
        public decimal BudgetTemmuz { get; set; }
        public decimal BudgetAgustos { get; set; }
        public decimal BudgetEylul { get; set; }
        public decimal BudgetEkim { get; set; }
        public decimal BudgetKasim { get; set; }
        public decimal BudgetAralik { get; set; }
        public decimal BudgetOcakTL { get; set; }
        public decimal BudgetSubatTL { get; set; }
        public decimal BudgetMartTL { get; set; }
        public decimal BudgetNisanTL { get; set; }
        public decimal BudgetMayisTL { get; set; }
        public decimal BudgetHaziranTL { get; set; }
        public decimal BudgetTemmuzTL { get; set; }
        public decimal BudgetAgustosTL { get; set; }
        public decimal BudgetEylulTL { get; set; }
        public decimal BudgetEkimTL { get; set; }
        public decimal BudgetKasimTL { get; set; }
        public decimal BudgetAralikTL { get; set; }
        public decimal BudgetOcakUSD { get; set; }
        public decimal BudgetSubatUSD { get; set; }
        public decimal BudgetMartUSD { get; set; }
        public decimal BudgetNisanUSD { get; set; }
        public decimal BudgetMayisUSD { get; set; }
        public decimal BudgetHaziranUSD { get; set; }
        public decimal BudgetTemmuzUSD { get; set; }
        public decimal BudgetAgustosUSD { get; set; }
        public decimal BudgetEylulUSD { get; set; }
        public decimal BudgetEkimUSD { get; set; }
        public decimal BudgetKasimUSD { get; set; }
        public decimal BudgetAralikUSD { get; set; }
        public decimal BudgetOcakEUR { get; set; }
        public decimal BudgetSubatEUR { get; set; }
        public decimal BudgetMartEUR { get; set; }
        public decimal BudgetNisanEUR { get; set; }
        public decimal BudgetMayisEUR { get; set; }
        public decimal BudgetHaziranEUR { get; set; }
        public decimal BudgetTemmuzEUR { get; set; }
        public decimal BudgetAgustosEUR { get; set; }
        public decimal BudgetEylulEUR { get; set; }
        public decimal BudgetEkimEUR { get; set; }
        public decimal BudgetKasimEUR { get; set; }
        public decimal BudgetAralikEUR { get; set; }
        public decimal LastBudgetOcak { get; set; }
        public decimal LastBudgetSubat { get; set; }
        public decimal LastBudgetMart { get; set; }
        public decimal LastBudgetNisan { get; set; }
        public decimal LastBudgetMayis { get; set; }
        public decimal LastBudgetHaziran { get; set; }
        public decimal LastBudgetTemmuz { get; set; }
        public decimal LastBudgetAgustos { get; set; }
        public decimal LastBudgetEylul { get; set; }
        public decimal LastBudgetEkim { get; set; }
        public decimal LastBudgetKasim { get; set; }
        public decimal LastBudgetAralik { get; set; }
        public decimal LastBudgetOcakTL { get; set; }
        public decimal LastBudgetSubatTL { get; set; }
        public decimal LastBudgetMartTL { get; set; }
        public decimal LastBudgetNisanTL { get; set; }
        public decimal LastBudgetMayisTL { get; set; }
        public decimal LastBudgetHaziranTL { get; set; }
        public decimal LastBudgetTemmuzTL { get; set; }
        public decimal LastBudgetAgustosTL { get; set; }
        public decimal LastBudgetEylulTL { get; set; }
        public decimal LastBudgetEkimTL { get; set; }
        public decimal LastBudgetKasimTL { get; set; }
        public decimal LastBudgetAralikTL { get; set; }
        public decimal LastBudgetOcakUSD { get; set; }
        public decimal LastBudgetSubatUSD { get; set; }
        public decimal LastBudgetMartUSD { get; set; }
        public decimal LastBudgetNisanUSD { get; set; }
        public decimal LastBudgetMayisUSD { get; set; }
        public decimal LastBudgetHaziranUSD { get; set; }
        public decimal LastBudgetTemmuzUSD { get; set; }
        public decimal LastBudgetAgustosUSD { get; set; }
        public decimal LastBudgetEylulUSD { get; set; }
        public decimal LastBudgetEkimUSD { get; set; }
        public decimal LastBudgetKasimUSD { get; set; }
        public decimal LastBudgetAralikUSD { get; set; }
        public decimal LastBudgetOcakEUR { get; set; }
        public decimal LastBudgetSubatEUR { get; set; }
        public decimal LastBudgetMartEUR { get; set; }
        public decimal LastBudgetNisanEUR { get; set; }
        public decimal LastBudgetMayisEUR { get; set; }
        public decimal LastBudgetHaziranEUR { get; set; }
        public decimal LastBudgetTemmuzEUR { get; set; }
        public decimal LastBudgetAgustosEUR { get; set; }
        public decimal LastBudgetEylulEUR { get; set; }
        public decimal LastBudgetEkimEUR { get; set; }
        public decimal LastBudgetKasimEUR { get; set; }
        public decimal LastBudgetAralikEUR { get; set; }
        public decimal ActualOcak { get; set; }
        public decimal ActualSubat { get; set; }
        public decimal ActualMart { get; set; }
        public decimal ActualNisan { get; set; }
        public decimal ActualMayis { get; set; }
        public decimal ActualHaziran { get; set; }
        public decimal ActualTemmuz { get; set; }
        public decimal ActualAgustos { get; set; }
        public decimal ActualEylul { get; set; }
        public decimal ActualEkim { get; set; }
        public decimal ActualKasim { get; set; }
        public decimal ActualAralik { get; set; }
        public decimal ActualOcakTL { get; set; }
        public decimal ActualSubatTL { get; set; }
        public decimal ActualMartTL { get; set; }
        public decimal ActualNisanTL { get; set; }
        public decimal ActualMayisTL { get; set; }
        public decimal ActualHaziranTL { get; set; }
        public decimal ActualTemmuzTL { get; set; }
        public decimal ActualAgustosTL { get; set; }
        public decimal ActualEylulTL { get; set; }
        public decimal ActualEkimTL { get; set; }
        public decimal ActualKasimTL { get; set; }
        public decimal ActualAralikTL { get; set; }
        public decimal ActualOcakUSD { get; set; }
        public decimal ActualSubatUSD { get; set; }
        public decimal ActualMartUSD { get; set; }
        public decimal ActualNisanUSD { get; set; }
        public decimal ActualMayisUSD { get; set; }
        public decimal ActualHaziranUSD { get; set; }
        public decimal ActualTemmuzUSD { get; set; }
        public decimal ActualAgustosUSD { get; set; }
        public decimal ActualEylulUSD { get; set; }
        public decimal ActualEkimUSD { get; set; }
        public decimal ActualKasimUSD { get; set; }
        public decimal ActualAralikUSD { get; set; }
        public decimal ActualOcakEUR { get; set; }
        public decimal ActualSubatEUR { get; set; }
        public decimal ActualMartEUR { get; set; }
        public decimal ActualNisanEUR { get; set; }
        public decimal ActualMayisEUR { get; set; }
        public decimal ActualHaziranEUR { get; set; }
        public decimal ActualTemmuzEUR { get; set; }
        public decimal ActualAgustosEUR { get; set; }
        public decimal ActualEylulEUR { get; set; }
        public decimal ActualEkimEUR { get; set; }
        public decimal ActualKasimEUR { get; set; }
        public decimal ActualAralikEUR { get; set; }
        public int BudgetOcakId { get; set; }
        public int BudgetSubatId { get; set; }
        public int BudgetMartId { get; set; }
        public int BudgetNisanId { get; set; }
        public int BudgetMayisId { get; set; }
        public int BudgetHaziranId { get; set; }
        public int BudgetTemmuzId { get; set; }
        public int BudgetAgustosId { get; set; }
        public int BudgetEylulId { get; set; }
        public int BudgetEkimId { get; set; }
        public int BudgetKasimId { get; set; }
        public int BudgetAralikId { get; set; }



    }
}
